create table if not exists projects (
 id uuid primary key, title varchar(120) not null, owner_id text not null references "user"(id), state text not null default 'active' check (state in ('active','archived','deleting')), revision bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists project_members (project_id uuid not null references projects(id), user_id text not null references "user"(id), added_by text not null references "user"(id), created_at timestamptz not null default now(), primary key(project_id,user_id));
create index if not exists project_members_user_idx on project_members(user_id);
create table if not exists board_objects (id uuid primary key, project_id uuid not null references projects(id), kind text not null, x double precision not null, y double precision not null, width double precision not null, height double precision not null, z_index integer not null, parent_id uuid null, data jsonb not null default '{}'::jsonb, version integer not null default 1, created_by text not null references "user"(id), updated_by text not null references "user"(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists board_objects_project_idx on board_objects(project_id);
create table if not exists board_connectors (id uuid primary key, project_id uuid not null references projects(id), data jsonb not null, version integer not null default 1, created_by text not null references "user"(id), updated_by text not null references "user"(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists board_connectors_project_idx on board_connectors(project_id);
create table if not exists command_receipts (project_id uuid not null, actor_id text not null, operation_id uuid not null, request_hash text not null, result jsonb not null, expires_at timestamptz not null, primary key(project_id,actor_id,operation_id));
create table if not exists media_assets (id uuid primary key, project_id uuid not null, dam_id text unique not null, object_id uuid, original_name text not null, mime_type text not null, byte_size bigint not null, state text not null, created_at timestamptz not null default now());
create table if not exists media_jobs (id uuid primary key, project_id uuid, asset_id uuid, operation text not null, state text not null default 'pending', dam_id text, attempts integer not null default 0, next_attempt_at timestamptz not null default now(), last_error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists media_jobs_due_idx on media_jobs(state,next_attempt_at);
create table if not exists mcp_sessions (id uuid primary key, token_hash text unique not null, user_id text not null references "user"(id), channel text not null default 'mcp', expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());
